shared:
  image: node:6
jobs:
  main:
    steps:
      - echo: commanddoesnotexist
      - laststep: meta set buildstatus passed
      - teardown-test: export STATUS=`meta get buildstatus`; echo $STATUS; if [ $STATUS=="passed" ]; then echo "good"; else echo "bad"; fi;
      - teardown-echo: echo bye
    environment:
        COVERAGE: 90
        API_URL: https://api.screwdriver.cd/v4/builds
    requires:
      - ~commit
  publish:
    steps:
      - echo: echo "This will not be triggered"
    requires:
      - main
