shared:
    image: node:6
jobs:
    test:
        steps:
            - echo: echo hi
        requires: ~commit
    test1:
        steps:
            - echo: sleep 20
    test2:
        steps:
            - echo: echo bye
        requires: [~test, ~test1]
