shared:
  image: node:6
jobs:
  firstjob:
    steps:
      - mystep: echo hi
      - fail: commanddoesnotexist
      - teardown-step1: echo hello
      - teardown-step2: echo world
    requires:
      - ~commit
