shared:
  image: node:6
jobs:
  main:
    steps:
      - echo: echo hi
      - laststep: meta set buildstatus passed
      - teardown-test: export STATUS=`meta get buildstatus`; if STATUS=='passed'; echo 'hello'; fi;
      - teardown-echo: echo bye
    environment:
        COVERAGE: 90
        API_URL: https://api.screwdriver.cd/v4/builds
    requires:
      - ~commit
  publish:
    steps:
      - echo: echo "This will not be triggered"
    requires:
      - main
