shared:
  image: node:6
jobs:
  main:
    steps:
      - echo: commanddoesnotexist
      - laststep: meta set buildstatus passed
      - teardown-test: export STATUS=`meta get buildstatus`; echo $STATUS; if [ $STATUS=="passed" ]; then echo "good"; else echo "bad"; fi;
    requires:
      - ~commit
